geospatial_log/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('geospatial_logs/', include('geospatial_logs.urls')),
    url(r'', include('geospatial_logs.urls', namespace='geospatial_logs')),
    url(r'^users/', include('users.urls', namespace='users'))
]

geospatial_logs/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'homepage'

urlpatterns = [
	# Домашняя страница
	url(r'^$', views.index, name='index'),
	# Страница со списком тем
	url(r'^topics/$', views.topics, name='topics'),
	# Страница с выводом информации по отдельнйой теме
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
	# Страница для добавления новой темы
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	# Страница для добавления новой записи
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	# Страница для редактирования записи
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.conf.urls import url
from django.contrib.auth import login

from django.contrib.auth.views import LoginView


from . import views

app_name = 'users'

urlpatterns = [
    # Страница входа.
    # url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login')]
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Страница выхода.
    url(r'^logout/$', views.logout_view, name='logout'),
    # Страница регистрации.
    url(r'^register/$', views.register, name='register'),

]

geospatial_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
	"""Тема, которую изучает пользователь"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, default = 4, on_delete=models.CASCADE)
	# owner = models.ForeignKey(User, default = 4, on_delete=models.CASCADE)

	def __str__(self):
		"""Возвращает строковое представление модели"""
		return self.text

class Entry(models.Model):
	"""Информация, изученная пользователем по теме"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Возвращает строковое представление модели."""
		if len(self.text) > 50:
			return self.text[:50] + "..."
		else:
			return self.text

users/models.py
from django.db import models

# Create your models here.

geospatial_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

geospatial_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def check_topic_owner(topic, request):
    if topic.owner != request.user:
        raise Http404

def index(request):
	"""Домашняя страница приложения geospatial_log"""
	return render(request, 'geospatial_logs/index.html')

@login_required
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'geospatial_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи"""
    # topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    # Проверка принадлежности темы текущему пользователю
    # if topic.owner != request.user:
    #     raise Http404
    check_topic_owner(topic, request)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'geospatial_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись - создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST - надо обработать.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('geospatial_logs:topics'))
    context = {'form':form}
    return render(request, 'geospatial_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по выбранной теме"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Данные не отправлялись - создается пустая форма.
        form = EntryForm()        
    else:
        # Отправлены данные POST - надо обработать.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            check_topic_owner(topic, request)
            new_entry.save()
            return HttpResponseRedirect(reverse('geospatial_logs:topic',
                                        args=[topic_id]))
    
    context = {'topic': topic, 'form': form}
    return render(request, 'geospatial_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Проверка принадлежности темы текущему пользователю
    # if topic.owner != request.user:
    #     raise Http404
    check_topic_owner(topic, request)
    if request.method != 'POST':
        # Исходный запрос. Форма заполняется текущими данными записи.
        form = EntryForm(instance=entry)
    else:
        # Отправлены данные POST - надо обработать.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('geospatial_logs:topic', args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'geospatial_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    """Завершает сеанс работы."""
    logout(request)
    return HttpResponseRedirect(reverse('geospatial_logs:index'))

def register(request):
    """Регистрация нового пользователя"""
    if request.method != 'POST':
        # Показать пустую рег.форму.   
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # Вход и перенаправление на дом.страницу.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('geospatial_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

geospatial_logs/templates/geospatial_logs/base.html
{% load bootstrap3 %}
<!-- Bootstrap 3 -->  


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>E-Note</title>


    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'geospatial_logs:index' %}">
              Стартовая страница</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'geospatial_logs:topics' %}">Темы</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Добро пожаловать, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Выход</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Регистрация</a></li>
              <li><a href="{% url 'users:login' %}">Войти</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->


  </body>
</html>

geospatial_logs/templates/geospatial_logs/edit_entry.html
{% extends "geospatial_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'geospatial_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Редактировать запись:</p>
    
  <form action="{% url 'geospatial_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Сохранить изменения</button>
  </form>

{% endblock content %}

geospatial_logs/templates/geospatial_logs/index.html
{% extends "geospatial_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
      <h1>E-Note</h1>        
  </div>
{% endblock %}

{% block content %}
  
  <h2>
    Делайте записи и разбивайте их по темам.
  </h2>
  <h4>
    <a href="{% url 'users:register' %}">Зарегистрируйте аккаунт</a> чтобы вести свой собственный
    E-Note.
  </h4>
{% endblock %}

geospatial_logs/templates/geospatial_logs/new_entry.html
{% extends "geospatial_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'geospatial_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Добавьте новую запись:</p>
  <form action="{% url 'geospatial_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>Новая запись</button>
  </form>
    
{% endblock content %}

geospatial_logs/templates/geospatial_logs/new_topic.html
{% extends "geospatial_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Добавить новую тему:</h2>
{% endblock header %}

{% block content %}
    
  <form action="{% url 'geospatial_logs:new_topic' %}" method='post'
      class="form">
      
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit" class="btn btn-primary">Новая тема</button>
    {% endbuttons %}
    
  </form>
    
{% endblock content %}

geospatial_logs/templates/geospatial_logs/topic.html
{% extends 'geospatial_logs/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'geospatial_logs:new_entry' topic.id %}">Добавить новую запись</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'geospatial_logs:edit_entry' entry.id %}">
              Редактировать запись</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel -->
  {% empty %}
    По этой теме еще нет записей.
  {% endfor %}

{% endblock content %}

geospatial_logs/templates/geospatial_logs/topics.html
{% extends 'geospatial_logs/base.html' %}

{% block header %}
  <h1>ТЕМЫ</h1>
{% endblock %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'geospatial_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
      </li>
    {% empty %}
      <li>Ни одной темы еще не добавлено.</li>
    {% endfor %}
  </ul>
  
  <h4><br><a href="{% url 'geospatial_logs:new_topic' %}">Добавить новую тему</br></h4>

{% endblock content %}

users/templates/users/login.html
{% extends "geospatial_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'geospatial_logs:index' %}" />
  </form>
    
{% endblock content %}

users/templates/users/register.html
{% extends "geospatial_logs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">Зарегистрироваться</button>
    <input type="hidden" name="next" value="{% url 'geospatial_logs:index' %}" />
  </form>
    
{% endblock content %}